# Specify location of manifest files for each package manager

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/apps/nextjs"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/apps/expo"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/api"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/config/tailwind"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/db"
    schedule:
      interval: "weekly"
